export const words = [
	"Accessory",
	"Adventure",
	"Advocate",
	"Africa",
	"Airport",
	"Airport",
	"Alarm",
	"Alcohol",
	"Alliance",
	"Ambulance",
	"America",
	"Ammo",
	"Angel",
	"Animal",
	"Antarctica",
	"Antiquity",
	"Appetite",
	"Apple",
	"Apprentice",
	"Apron",
	"Archaeology",
	"Architecture",
	"Arm",
	"Armor",
	"Arrow",
	"Asia",
	"Assassin",
	"Asset",
	"Astronaut",
	"Attack",
	"Attraction",
	"Autumn",
	"Award",
	"Axe",
	"Baby",
	"Bag",
	"Bakery",
	"Balance",
	"Balcony",
	"Ball",
	"Ballroom",
	"Banana",
	"Band",
	"Bang",
	"Bank",
	"Bar",
	"Bark",
	"Barn",
	"Barracks",
	"Base",
	"Basement",
	"Basket",
	"Bath",
	"Battery",
	"Bay",
	"Beach",
	"Bear",
	"Beard",
	"Beast",
	"Bed",
	"Bedroom",
	"Beef",
	"Beer",
	"Belgium",
	"Bell",
	"Belt",
	"Bench",
	"Berry",
	"Big",
	"Bike",
	"Bill",
	"Bin",
	"Bird",
	"Birthday",
	"Bite",
	"Black",
	"Blade",
	"Blanket",
	"Blond",
	"Blood",
	"Blue",
	"Board",
	"Boat",
	"Body",
	"Bomb",
	"Bone",
	"Book",
	"Boot",
	"Border",
	"Boss",
	"Bottle",
	"Bottom",
	"Bouquet",
	"Bowl",
	"Box",
	"Boxing",
	"Bracelet",
	"Brain",
	"Branch",
	"Bread",
	"Bridge",
	"Bronze",
	"Broom",
	"Brother",
	"Brown",
	"Brush",
	"Bubble",
	"Bucket",
	"Buckle",
	"Bug",
	"Building",
	"Bulb",
	"Bump",
	"Bus",
	"Business",
	"Butcher",
	"Butterfly",
	"Button",
	"Cabbage",
	"Cabin",
	"Cable",
	"Cactus",
	"Cage",
	"Cake",
	"Calendar",
	"Camera",
	"Camouflage",
	"Camp",
	"Canal",
	"Candle",
	"Candy",
	"Cane",
	"Cannon",
	"Cantina",
	"Canvas",
	"Capital",
	"Captain",
	"Car",
	"Card",
	"Career",
	"Carpet",
	"Carrot",
	"Carton",
	"Case",
	"Casino",
	"Castle",
	"Cat",
	"Caterpillar",
	"Cavalry",
	"Cave",
	"Cavern",
	"Cell",
	"Cemetery",
	"Cereal",
	"Chain",
	"Chair",
	"Challenge",
	"Chameleon",
	"Champagne",
	"Champion",
	"Charge",
	"Chariot",
	"Charm",
	"Chef",
	"Chess",
	"Cheese",
	"Chest",
	"Chick",
	"Child",
	"Chimney",
	"China",
	"Chocolate",
	"Church",
	"Cigarette",
	"Cinema",
	"Circle",
	"Circus",
	"Claw",
	"Clean",
	"Climbing",
	"Closet",
	"Clothing",
	"Cloud",
	"Clown",
	"Club",
	"Cockroach",
	"Cocktail",
	"Coffee",
	"Cold",
	"Color",
	"Column",
	"Comedy",
	"Comforter",
	"Commerce",
	"Common",
	"Computer",
	"Concert",
	"Console",
	"Cookie",
	"Cork",
	"Cotton",
	"Couch",
	"Cougar",
	"Country",
	"Court",
	"Covered",
	"Cow",
	"Crab",
	"Craft",
	"Crane",
	"Cream",
	"Crescent",
	"Cross",
	"Crown",
	"Crown",
	"Cube",
	"Cuddle",
	"Cup",
	"Currency",
	"Curry",
	"Curtain",
	"Cushion",
	"Dance",
	"Danger",
	"Day",
	"Dead",
	"Decor",
	"Deep",
	"Defense",
	"Degree",
	"Delivery",
	"Demon",
	"Desert",
	"Dessert",
	"Detective",
	"Detergent",
	"Device",
	"Devil",
	"Diamond",
	"Dictator",
	"Diet",
	"Dinosaur",
	"Dirty",
	"Dish",
	"Display",
	"Distributor",
	"District",
	"Doctor",
	"Doe",
	"Dog",
	"Doll",
	"Donkey",
	"Door",
	"Double",
	"Dough",
	"Down",
	"Dragon",
	"Drawing",
	"Dream",
	"Dress",
	"Dresser",
	"Drink",
	"Drum",
	"Duck",
	"Dungeon",
	"Dwarf",
	"Dynamite",
	"Ear",
	"Earth",
	"Edge",
	"Egg",
	"Elastic",
	"Electricity",
	"Emergency",
	"End",
	"Engine",
	"Entry",
	"Envelop",
	"Essence",
	"Europe",
	"Evening",
	"Exhibition",
	"Exit",
	"Explore",
	"Explosion",
	"Eye",
	"Fable",
	"Face",
	"Fair",
	"Fairy",
	"Family",
	"farm",
	"Fashion",
	"Fast",
	"Father",
	"Fault",
	"Feather",
	"Feed",
	"Feline",
	"Fever",
	"Field",
	"File",
	"Finger",
	"Fire",
	"Firefighter",
	"First",
	"Fish",
	"Fishing",
	"Flame",
	"Flash",
	"Flask",
	"Flea",
	"Flight",
	"Flour",
	"Flower",
	"Flute",
	"Fly",
	"Foam",
	"Food",
	"Fool",
	"Foot",
	"Forbidden",
	"Forecast",
	"Forest",
	"Fountain",
	"Fox",
	"Frame",
	"France",
	"Friend",
	"Frost",
	"Fruit",
	"Fry",
	"Fuel",
	"Full",
	"Fur",
	"Furniture",
	"Gamble",
	"Game",
	"Garage",
	"Garbage",
	"Garden",
	"Gas",
	"Gate",
	"Genius",
	"Ghost",
	"Giant",
	"Gift",
	"Glass",
	"Glasses",
	"Glove",
	"God",
	"Gold",
	"Grain",
	"Grape",
	"Grass",
	"Grate",
	"Grave",
	"Grease",
	"Green",
	"Grenade",
	"Grey",
	"Ground",
	"Group",
	"Guardian",
	"Guide",
	"Guitar",
	"Hair",
	"Hall",
	"Hammer",
	"Handicap",
	"Handle",
	"Handle",
	"Hard",
	"Hardware",
	"Hat",
	"Head",
	"Hearing",
	"Heart",
	"Hearth",
	"Heavy",
	"Heel",
	"Hell",
	"Helmet",
	"Hen",
	"Herbs",
	"Heritage",
	"Hero",
	"Heroine",
	"Hide",
	"High",
	"History",
	"Hobbies",
	"Hole",
	"Honey",
	"Hood",
	"Hook",
	"Horse",
	"Hospital",
	"Hot",
	"Hotel",
	"House",
	"Human",
	"Humour",
	"Hunt",
	"Ice",
	"Illness",
	"Ink",
	"Inside",
	"Inspection",
	"Instrument",
	"Internet",
	"Intersection",
	"Ireland",
	"Iron",
	"Island",
	"Jar",
	"Jelly",
	"Jewel",
	"Joke",
	"Judge",
	"Jump",
	"Jungle",
	"Key",
	"King",
	"Kiss",
	"Kitchen",
	"Knife",
	"Knight",
	"Knot",
	"Labyrinth",
	"Ladder",
	"Ladle",
	"Lady",
	"Ladybug",
	"Lake",
	"Lamp",
	"Landscape",
	"Large",
	"Laser",
	"Laugh",
	"Lava",
	"Layer",
	"Lazy",
	"Leaf",
	"Leak",
	"Lemon",
	"Letter",
	"Library",
	"Life",
	"Light",
	"Lighter",
	"Lighthouse",
	"Lightning",
	"Limb",
	"Limit",
	"Line",
	"Lion",
	"Liquid",
	"Lock",
	"Log",
	"Loop",
	"Love",
	"Luck",
	"Luxury",
	"Machine",
	"Magic",
	"Magician",
	"Magnet",
	"Microscope",
	"Mail",
	"Major",
	"Map",
	"March",
	"Marine",
	"Mark",
	"Marker",
	"Market",
	"Marriage",
	"Mask",
	"Mass",
	"Master",
	"Match",
	"Matter",
	"Medal",
	"Medusa",
	"Melon",
	"Memory",
	"Menu",
	"Metal",
	"Middle",
	"Military",
	"Milk",
	"Mind",
	"Minor",
	"Mint",
	"Mirage",
	"Mirror",
	"Missile",
	"Mobile",
	"Moist",
	"Monster",
	"Month",
	"Moon",
	"Morning",
	"Mosquito",
	"Mother",
	"Motor",
	"Mountain",
	"Mouse",
	"Moustache",
	"Mouth",
	"Movie",
	"Mud",
	"Mug",
	"Mummy",
	"Museum",
	"Mushroom",
	"Music",
	"Mustard",
	"Myth",
	"Nail",
	"Napkin",
	"Necklace",
	"Needle",
	"Nerve",
	"Nest",
	"New",
	"Newspaper",
	"Night",
	"Nightmare",
	"Noodle",
	"North",
	"Note",
	"Nude",
	"Nurse",
	"Nut",
	"Oak",
	"Oar",
	"Oasis",
	"Ocean",
	"Octopus",
	"Office",
	"Oil",
	"Old",
	"Orange",
	"Orchard",
	"Order",
	"Outlet",
	"Oven",
	"Owl",
	"Pad",
	"Padlock",
	"Paintbrush",
	"Painting",
	"Pair",
	"Palace",
	"Pan",
	"Paper",
	"Paradise",
	"Park",
	"Party",
	"Passion",
	"Past",
	"Patio",
	"Patron",
	"Peace",
	"Pear",
	"Pearl",
	"Pepper",
	"Performance",
	"Perfume",
	"Permanent",
	"Phone",
	"Photo",
	"Physical",
	"Piano",
	"Picture",
	"Pie",
	"Pig",
	"Pigeon",
	"Pilot",
	"Pine",
	"Pipe",
	"Pirate",
	"Pit",
	"Pizza",
	"Place",
	"Plane",
	"Plank",
	"Plant",
	"Plastic",
	"Pliers",
	"Plush",
	"Pocket",
	"Poetry",
	"Poison",
	"Polar",
	"Police",
	"Pond",
	"Porcelain",
	"Port",
	"Post",
	"Potato",
	"Powder",
	"Press",
	"Princess",
	"Prison",
	"Promotion",
	"Protect",
	"Pump",
	"Pumpkin",
	"Punch",
	"Puzzle",
	"Pyramid",
	"Queen",
	"Quilt",
	"Rabbit",
	"Race",
	"Radar",
	"Radio",
	"Raft",
	"Rail",
	"Rain",
	"Rake",
	"Ramp",
	"Rat",
	"Ray",
	"Recent",
	"Recipe",
	"Recipient",
	"Record",
	"Red",
	"Region",
	"Religion",
	"Repair",
	"Report",
	"Reptile",
	"Restaurant",
	"Revenge",
	"Revolution",
	"Revolver",
	"Rice",
	"Rich",
	"Rifle",
	"Right",
	"Ring",
	"River",
	"Road",
	"Roast",
	"Robot",
	"Roll",
	"Roof",
	"Room",
	"Rooster",
	"Root",
	"Rope",
	"Rose",
	"Round",
	"Ruin",
	"Ruler",
	"Sabre",
	"Safari",
	"Sage",
	"Sail",
	"Salad",
	"Salt",
	"Sand",
	"Sausage",
	"Schedule",
	"School",
	"Science",
	"Scissors",
	"Screen",
	"Screw",
	"Sea",
	"Season",
	"Secret",
	"Sense",
	"Series",
	"Sewer",
	"Shadow",
	"Shape",
	"Shark",
	"Sharp",
	"Shed",
	"Sheep",
	"Shelf",
	"Shell",
	"Shelter",
	"Shield",
	"Ship",
	"Shirt",
	"Shop",
	"Short",
	"Shovel",
	"Show",
	"Shower",
	"Sight",
	"Silence",
	"Silver",
	"Siren",
	"Sister",
	"Size",
	"Skate",
	"Skeleton",
	"Skin",
	"Skull",
	"Sky",
	"Sleeve",
	"Slide",
	"Slow",
	"Small",
	"Smell",
	"Smoke",
	"Snack",
	"Snail",
	"Snake",
	"Snow",
	"Soap",
	"Sock",
	"Soft",
	"Soldier",
	"Solitary",
	"Song",
	"Sound",
	"Soup",
	"Space",
	"Speaker",
	"Spear",
	"Species",
	"Spice",
	"Spicy",
	"Spider",
	"Sponge",
	"Sport",
	"Spring",
	"Spy",
	"Square",
	"Stage",
	"Stamp",
	"Star",
	"Station",
	"Statue",
	"Stick",
	"Sticky",
	"Stitches",
	"Stocks",
	"Stone",
	"Storm",
	"Story",
	"Straw",
	"Strength",
	"String",
	"Stroke",
	"Strong",
	"Stud",
	"Studio",
	"Stunt",
	"Stylist",
	"Subway",
	"Sugar",
	"Suit",
	"Suitcase",
	"Suite",
	"Summer",
	"Summit",
	"Sun",
	"Sunday",
	"Surgeon",
	"Suspect",
	"Sweet",
	"Swing",
	"Switzerland",
	"Sword",
	"Syrup",
	"Table",
	"Tail",
	"Talent",
	"Tame",
	"Tank",
	"Target",
	"Taste",
	"Tattoo",
	"Tea",
	"Technology",
	"Television",
	"Temple",
	"Tennis",
	"Tent",
	"Theatre",
	"Thermometer",
	"Thief",
	"Thin",
	"Thread",
	"Throat",
	"Thunder",
	"Ticket",
	"Tiger",
	"Tile",
	"Tiny",
	"Tobacco",
	"Toilet",
	"Tomato",
	"Tongue",
	"Tool",
	"Top",
	"Tornado",
	"Town",
	"Toy",
	"Track",
	"Trade",
	"Tradition",
	"Trailer",
	"Train",
	"Transport",
	"Trash",
	"Travel",
	"Treasure",
	"Tree",
	"Triangle",
	"Trim",
	"Trophy",
	"Truck",
	"Tube",
	"Tunnel",
	"Turn",
	"Turnip",
	"Turtle",
	"Twins",
	"Umbrella",
	"Underground",
	"Uniform",
	"Union",
	"Universe",
	"Utensil",
	"Vacation",
	"Vampire",
	"Vegetable",
	"Victory",
	"Violin",
	"Virgin",
	"Virus",
	"Vision",
	"Voice",
	"Volcano",
	"Volume",
	"Waiter",
	"Walk",
	"Wand",
	"War",
	"Watch",
	"Water",
	"Wave",
	"Weak",
	"Weapon",
	"Weather",
	"Weight",
	"Well",
	"Whale",
	"Wheat",
	"Wheel",
	"Whip",
	"Whirlwind",
	"White",
	"Wild",
	"Wind",
	"Window",
	"Wine",
	"Wing",
	"Winter",
	"Wish",
	"Witness",
	"Wizard",
	"Wolf",
	"Wood",
	"Wool",
	"Work",
	"Yellow",
	"Young",
	"Zoo",
]

export const cards = [
	["Accessory", "Brain", "Alarm", "Space"],
	["Adventure", "Red", "Line", "Umbrella"],
	["Advocate", "Fur", "Chain", "Cold"],
	["Africa", "Liquid", "Twins", "Patio"],
	["Airport", "Sport", "Currency", "Mirage"],
	["Airport", "Police", "Double", "Silence"],
	["Alcohol", "Nude", "Well", "Rooster"],
	["Alliance", "Cabin", "Old", "Tiger"],
	["Ambulance", "Fox", "Mountain", "Dictator"],
	["America", "Wand", "Pigeon", "Robot"],
	["Ammo", "Vacation", "Rose", "Volume"],
	["Angel", "Key", "Bed", "Zoo"],
	["Animal", "Map", "Waiter", "Fool"],
	["Antarctica", "Armor", "Curtain", "Charge"],
	["Antiquity", "Exit", "Plant", "Candle"],
	["Appetite", "War", "Heart", "Gas"],
	["Apple", "Common", "Exhibition", "Ship"],
	["Apprentice", "Heritage", "Bedroom", "Mustard"],
	["Apron", "Cube", "Degree", "Siren"],
	["Archaeology", "Cork", "Distributor", "Plush"],
	["Architecture", "Family", "Flame", "Sleeve"],
	["Arm", "Work", "Cream", "Laser"],
	["Arrow", "Shadow", "Picture", "Market"],
	["Asia", "Glove", "Shape", "Ground"],
	["Assassin", "Powder", "Labyrinth", "Party"],
	["Asset", "Race", "Closet", "Rain"],
	["Astronaut", "Fish", "Padlock", "Inside"],
	["Attack", "Dough", "Queen", "Water"],
	["Attraction", "Rake", "Tongue", "Wizard"],
	["Autumn", "Machine", "Curry", "Underground"],
	["Award", "Fly", "Calendar", "Skull"],
	["Axe", "Board", "Button", "Union"],
	["Baby", "Sight", "Base", "Subway"],
	["Bag", "Thin", "Rice", "Balcony"],
	["Bakery", "Tent", "Noodle", "Weapon"],
	["Balance", "Universe", "Chameleon", "Wheel"],
	["Ball", "Night", "Tree", "School"],
	["Ballroom", "Hen", "Bike", "Mirror"],
	["Banana", "Tattoo", "Doe", "Clothing"],
	["Band", "Bone", "Marine", "Spring"],
	["Bang", "Owl", "Ruin", "Stamp"],
	["Bank", "Lava", "Dessert", "God"],
	["Bar", "Strong", "Knife", "Caterpillar"],
	["Bark", "Wind", "China", "Belt"],
	["Barn", "Explore", "Giant", "Bucket"],
	["Barracks", "Kiss", "Duck", "Trim"],
	["Basement", "Sun", "Concert", "Cable"],
	["Basket", "Weak", "Knight", "Toy"],
	["Bath", "Nerve", "Plane", "Nut"],
	["Battery", "Carpet", "Laugh", "Luxury"],
	["Bay", "Pipe", "Magic", "Slow"],
	["Beach", "Morning", "Head", "Device"],
	["Bear", "Solitary", "Grave", "Train"],
	["Beard", "North", "Bottle", "Group"],
	["Beast", "Volcano", "Root", "Screen"],
	["Beef", "Doctor", "Mark", "Chair"],
	["Beer", "Marker", "Technology", "Edge"],
	["Belgium", "Sharp", "Carton", "Snake"],
	["Bell", "Fruit", "Whale", "Wild"],
	["Bench", "Patron", "Stud", "Camera"],
	["Berry", "Electricity", "Spy", "Tube"],
	["Big", "Business", "Dish", "Myth"],
	["Bill", "Tank", "Challenge", "Friend"],
	["Bin", "Forbidden", "Hammer", "Drawing"],
	["Bird", "Treasure", "Nurse", "Sticky"],
	["Birthday", "Press", "Military", "Dinosaur"],
	["Bite", "Fashion", "Movie", "Tile"],
	["Black", "Hunt", "Thread", "Sponge"],
	["Blade", "Peace", "Bowl", "Mouth"],
	["Blanket", "Pearl", "Carrot", "Lady"],
	["Blond", "Trailer", "Decor", "Recipe"],
	["Blood", "Microscope", "Report", "String"],
	["Blue", "Tunnel", "Dress", "Vision"],
	["Boat", "Iron", "Whirlwind", "Wine"],
	["Body", "Cat", "Record", "Monster"],
	["Bomb", "Food", "Gift", "Library"],
	["Book", "Soft", "Poison", "Diamond"],
	["Boot", "Rat", "Gate", "Ray"],
	["Border", "Log", "Master", "Skin"],
	["Boss", "Color", "Rifle", "Post"],
	["Bottom", "Leaf", "Career", "Swing"],
	["Bouquet", "Box", "Eye", "Sea"],
	["Boxing", "First", "Fever", "Building"],
	["Bracelet", "Deep", "Region", "Cemetery"],
	["Branch", "Quilt", "Soap", "Full"],
	["Bread", "Chess", "Mummy", "Flight"],
	["Bridge", "Defense", "Piano", "Sense"],
	["Bronze", "Sabre", "Broom", "Tradition"],
	["Brother", "Grate", "Envelop", "Turnip"],
	["Brown", "Covered", "Furniture", "Comforter"],
	["Brush", "Travel", "Flower", "Fishing"],
	["Bubble", "Poetry", "Sweet", "Nest"],
	["Buckle", "Sword", "Grease", "Wish"],
	["Bug", "Genius", "Jewel", "Summit"],
	["Bulb", "Cake", "Princess", "Cactus"],
	["Bump", "Green", "Pie", "Cage"],
	["Bus", "Egg", "Nail", "Newspaper"],
	["Butcher", "Smoke", "Needle", "Knot"],
	["Butterfly", "Road", "Cocktail", "Face"],
	["Cabbage", "Stunt", "Month", "Stroke"],
	["Camouflage", "Salad", "Young", "Ocean"],
	["Camp", "Crescent", "Outlet", "Size"],
	["Canal", "Wheat", "Museum", "Roof"],
	["Candy", "Court", "Danger", "Grass"],
	["Cane", "Wool", "Dungeon", "Ring"],
	["Cannon", "Potato", "Champion", "Permanent"],
	["Cantina", "Lightning", "Phone", "Music"],
	["Canvas", "Punch", "Soup", "Game"],
	["Capital", "Doll", "Past", "Flash"],
	["Captain", "Father", "Internet", "Snack"],
	["Car", "Small", "Humour", "Garbage"],
	["Card", "Porcelain", "Pump", "Season"],
	["Case", "Pepper", "Fast", "Light"],
	["Casino", "Mind", "Moon", "Hide"],
	["Castle", "Frost", "Plastic", "Detergent"],
	["Cavalry", "Minor", "White", "Fable"],
	["Cave", "Mosquito", "Magician", "Studio"],
	["Cavern", "Shark", "Feed", "Ear"],
	["Cell", "Console", "Voice", "Recipient"],
	["Cereal", "Evening", "Plank", "Oasis"],
	["Champagne", "Switzerland", "Cockroach", "Landscape"],
	["Chariot", "Limb", "Napkin", "Perfume"],
	["Charm", "Tame", "Flour", "Sail"],
	["Chef", "Square", "Salt", "Cotton"],
	["Cheese", "Illness", "Column", "Cloud"],
	["Chest", "Pit", "Paintbrush", "Nightmare"],
	["Chick", "Fountain", "Ice", "Walk"],
	["Child", "Shirt", "Tail", "Menu"],
	["Chimney", "Clean", "Story", "Jar"],
	["Chocolate", "Office", "Pair", "Protect"],
	["Church", "Table", "Mushroom", "Truck"],
	["Cigarette", "Stick", "Country", "Secret"],
	["Cinema", "Cup", "Jump", "Dream"],
	["Circle", "Sock", "Door", "Cow"],
	["Circus", "Ladder", "Pilot", "Skate"],
	["Claw", "Mud", "Grenade", "Trash"],
	["Climbing", "Pond", "Firefighter", "Sheep"],
	["Clown", "Feline", "Garage", "Tobacco"],
	["Club", "Loop", "Stylist", "Pyramid"],
	["Coffee", "Puzzle", "Cougar", "Stone"],
	["Comedy", "Pocket", "Suite", "Missile"],
	["Commerce", "Trophy", "Shovel", "End"],
	["Computer", "Demon", "Revolver", "Jelly"],
	["Cookie", "Craft", "Shell", "Flea"],
	["Couch", "farm", "Helmet", "Strength"],
	["Crab", "Passion", "Field", "Flute"],
	["Crane", "District", "Lazy", "Stocks"],
	["Cross", "Hot", "Dwarf", "Science"],
	["Crown", "Dance", "Prison", "Matter"],
	["Crown", "Handle", "River", "Radio"],
	["Cuddle", "New", "Violin", "Fairy"],
	["Cushion", "Necklace", "Oil", "Vampire"],
	["Day", "Shield", "Inspection", "History"],
	["Dead", "Radar", "Reptile", "Major"],
	["Delivery", "Song", "Station", "Throat"],
	["Desert", "Paper", "Virus", "Honey"],
	["Detective", "Town", "Sky", "Spice"],
	["Devil", "Mint", "Recent", "Layer"],
	["Diet", "Explosion", "Top", "Show"],
	["Dirty", "Medal", "Wave", "Fair"],
	["Display", "Octopus", "Right", "Forest"],
	["Dog", "Ramp", "Television", "Lemon"],
	["Donkey", "Virgin", "Mug", "Park"],
	["Down", "Guide", "Love", "Memory"],
	["Dragon", "Europe", "Repair", "Victory"],
	["Dresser", "Suitcase", "Judge", "Herbs"],
	["Drink", "Horse", "Polar", "Short"],
	["Drum", "Fire", "Sister", "Hotel"],
	["Dynamite", "Pliers", "Slide", "Snail"],
	["Earth", "Mouse", "Yellow", "Toilet"],
	["Elastic", "Triangle", "Weather", "Order"],
	["Emergency", "Metal", "Lighthouse", "Hero"],
	["Engine", "Letter", "Safari", "Sewer"],
	["Entry", "Round", "Sand", "Oven"],
	["Essence", "Joke", "Hospital", "Roast"],
	["Fault", "France", "Physical", "Rabbit"],
	["Feather", "Pan", "Orange", "Tiny"],
	["File", "Magnet", "Tennis", "Shop"],
	["Finger", "Note", "Hard", "Kitchen"],
	["Flask", "Marriage", "Target", "Leak"],
	["Foam", "Handle", "Talent", "Vegetable"],
	["Foot", "Winter", "Island", "High"],
	["Forecast", "Screw", "Tomato", "Grey"],
	["Frame", "Weight", "Pumpkin", "Jungle"],
	["Fry", "Ruler", "Mail", "Revolution"],
	["Fuel", "Luck", "Roll", "Hook"],
	["Gamble", "Mask", "Sugar", "Port"],
	["Garden", "Spear", "Ink", "Stitches"],
	["Ghost", "Storm", "Pad", "Soldier"],
	["Glass", "Turn", "Hobbies", "Series"],
	["Glasses", "Syrup", "King", "Place"],
	["Gold", "Melon", "Lake", "Sound"],
	["Grain", "Shed", "Turtle", "Statue"],
	["Grape", "Shower", "Utensil", "Middle"],
	["Guardian", "Moist", "Sunday", "Wolf"],
	["Guitar", "Thermometer", "Lock", "Schedule"],
	["Hair", "Tool", "Hall", "Heroine"],
	["Handicap", "Lion", "Rich", "Star"],
	["Hardware", "Ticket", "Witness", "Sausage"],
	["Hat", "Large", "Pine", "Spicy"],
	["Hearing", "Ladle", "Hearth", "Stage"],
	["Heavy", "Tea", "Room", "Life"],
	["Heel", "Revenge", "Watch", "Motor"],
	["Hell", "Track", "Milk", "Taste"],
	["Hole", "March", "Wood", "Skeleton"],
	["Hood", "Pear", "Lamp", "House"],
	["Human", "Window", "Uniform", "Whip"],
	["Instrument", "Limit", "Pirate", "Intersection"],
	["Ireland", "Medusa", "Lighter", "Shelter"],
	["Ladybug", "Restaurant", "Painting", "Speaker"],
	["Mass", "Photo", "Orchard", "Performance"],
	["Match", "Mother", "Rope", "Paradise"],
	["Mobile", "Oak", "Raft", "Suspect"],
	["Moustache", "Surgeon", "Silver", "Pizza"],
	["Oar", "Thief", "Theatre", "Smell"],
	["Palace", "Wing", "Snow", "Scissors"],
	["Pig", "Sage", "Trade", "Rail"],
	["Promotion", "Thunder", "Straw", "Religion"],
	["Shelf", "Tornado", "Spider", "Transport"],
	["Species", "Temple", "Suit", "Summer"],
]